#version 460

layout (local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
layout (rgba32f, binding = 0) uniform image2D imgOut;

uniform float time;

void main()
{
    vec2 fragCoord  = vec2(gl_GlobalInvocationID.xy);
    vec2 resolution = vec2(gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);
    vec2 uv         = (2.0*fragCoord - resolution) / resolution.y;

    vec3 col = vec3(sin(time) * uv.x, cos(time) * uv.y, 0.0);

    imageStore(imgOut, ivec2(fragCoord), vec4(col, 1.0));
}